In [4]:
# Dependencies
import pandas as pd
import requests
import time
import json
import operator as op
import numpy as np
import hvplot.pandas
from config import api_key
from scipy.stats import linregress
from matplotlib import pyplot as plt

In [5]:
# Import cities file as DataFrame
data_df = pd.read_csv("athlete_events.csv")
data_df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [6]:
# checking columns of dataframe
data_df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')

In [7]:
# Unique cities that held Olympic games
cities_held_games = data_df['City'].unique()
cities_held_games

array(['Barcelona', 'London', 'Antwerpen', 'Paris', 'Calgary',
       'Albertville', 'Lillehammer', 'Los Angeles', 'Salt Lake City',
       'Helsinki', 'Lake Placid', 'Sydney', 'Atlanta', 'Stockholm',
       'Sochi', 'Nagano', 'Torino', 'Beijing', 'Rio de Janeiro', 'Athina',
       'Squaw Valley', 'Innsbruck', 'Sarajevo', 'Mexico City', 'Munich',
       'Seoul', 'Berlin', 'Oslo', "Cortina d'Ampezzo", 'Melbourne',
       'Roma', 'Amsterdam', 'Montreal', 'Moskva', 'Tokyo', 'Vancouver',
       'Grenoble', 'Sapporo', 'Chamonix', 'St. Louis', 'Sankt Moritz',
       'Garmisch-Partenkirchen'], dtype=object)

In [8]:
summer_host_data = pd.read_csv("summer_host_cities.csv")
summer_host_data.head()

  summer_host_city      Continent
0          Â Greece         Europe
1          Â France         Europe
2   Â United States  North America
3  Â United Kingdom         Europe
4          Â Sweden         Europe

In [9]:
summer_host_data_clean = summer_host_data.dropna()
summer_host_data_clean

                                     summer_host_city      Continent
0                                             Â Greece         Europe
1                                             Â France         Europe
2                                      Â United States  North America
3                                     Â United Kingdom         Europe
4                                             Â Sweden         Europe
5                                            Â Belgium         Europe
6                                        Â Netherlands         Europe
7                                            Â Germany         Europe
8                                            Â Finland         Europe
9                                          Â Australia        Oceania
10                                             Â Italy         Europe
11                                             Â Japan           Asia
12                                            Â Mexico   Noth America
13                                      Â West Germany         Europe
14                                            Â Canada   Noth America
15                                      Â Soviet Union         Europe
16                                       Â South Korea           Asia
17                                             Â Spain         Europe
18                                             Â China           Asia
19                                            Â Brazil  South America
20  Â Japan (postponed to 2021 due to the coronavir...           Asia

In [10]:
winter_host_data = pd.read_csv("winter_host_cities.csv")
winter_host_data.head()

  winter_host_country      continent
0             Â France         Europe
1        Â Switzerland         Europe
2      Â United States  North America
3            Â Germany         Europe
4             Â Norway         Europe

In [11]:
winter_host_data_clean = winter_host_data.dropna()
winter_host_data_clean

   winter_host_country      continent
0              Â France         Europe
1         Â Switzerland         Europe
2       Â United States  North America
3             Â Germany         Europe
4              Â Norway         Europe
5               Â Italy         Europe
6             Â Austria         Europe
7               Â Japan           Asia
8          Â Yugoslavia         Europe
9              Â Canada  North America
10             Â Russia         Europe
11        Â South Korea           Asia
12              Â China           Asia

In [12]:
countries_vs_continents = pd.read_csv("all_host_cities.csv")
countries_vs_continents.head()

  all_host_countries      continent
0         Â Australia        Oceania
1           Â Austria         Europe
2           Â Belgium         Europe
3            Â Brazil  South America
4            Â Canada  North America

In [13]:
cities_coordinates = pd.read_csv("olym.csv")
cities_coordinates.head()

        City         Country  NOC Summer Winter  Year   Latitude  Longitude
0     Athens          Greece  GRE      I    NaN  1896  37.983333  23.733334
1      Paris          France  FRA     II    NaN  1900  48.853410   2.348800
2  St. Louis   United States  USA    III    NaN  1904  38.627273 -90.197891
3     London  United Kingdom  GBR     IV    NaN  1908  51.508415  -0.125533
4  Stockholm          Sweden  SWE      V    NaN  1912  59.332577  18.064903

In [15]:
%%capture --no-display

# Configure the map plot
plot_1 = cities_coordinates.hvplot.points(
    'Longitude',
    'Latitude',
    geo=True, 
    tiles = 'OSM', 
    frame_width = 700, 
    frame_height = 500, 
    color='City',
    alpha= 0.5,
    title='Host Cities from 1896 - 2016',
    scale= 0.8)

# Display the map
plot_1

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [Longitude,Latitude]   (City)